# This is a basic workflow to help you get started with Actions

name: Secrets and Environment Variable

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    # The type of runner that the job will run on
  top-secret:
    runs-on: ubuntu-latest

    env:
      MY_API_KEY: ${{vars.API.KEY}}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Read a variable
        run: echo "My API-KEY is ${{vars.API_KEY}}"

      - name: Tell me a secret
        run: echo "My API-KEY is ${{secrets.API_KEY}}"

      - name: unset secret
        run: echo "My API-KEY is ${{secrets.DOES NOT EXIST}}"

      - name: githubb stuff
        run: echo "My API-KEY is ${{github.repository}}"

      - name: Read a env variable
        run: echo "My API-KEY is ${{env.API_KEY}}"

      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      # - name: Run the env from external script
      #   run: 
      #     chmod +x .github/scripts/custom.sh
      #     .github/scripts/custom.sh
      #   shell: bash
